### PR TITLE
Add example Kubernetes integration

### PR DESCRIPTION
**Pull request by dhemeier**
Okay, Kubernetes example completed 👌

### CODE REVIEW

**Comment by crazy-max** [comment]
@dhemeier Can you create a new section about k8s [here](https://github.com/crazy-max/docker-matomo#use-this-image) that points to your README ?

**Comment by dhemeier** [comment]
I hate CGLs when I have not configured my IDE :-( @crazy-max could you please tell my what's wrong with the list items? When I add 2 spaces, it says remove, when I remove it says add 2 spaces -_-

**Comment by crazy-max** [comment]
@dhemeier Yeah it's BS from Codacy, I have disabled Makrdown analysis for now ;)

**Comment by dhemeier** [comment]
Okay, I would say then its done ;-)

**Comment by crazy-max** [comment]
Done thanks again :)

**Pull request merged**
