### PR TITLE
gzip all API calls

### PR DESCRIPTION
**Pull request by toredash**
With the current config some API calls won't be compressed. Force compression for all files for requests in the given location

### CODE REVIEW

**Comment by toredash** [comment]
Example API call that isn't compressed:
`index.php?forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&idSite=8&period=month&date=2019-04-16&showtitle=1&random=8752'`

**Comment by crazy-max** [comment]
@toredash Compression is [already enabled](https://github.com/crazy-max/docker-matomo/blob/master/assets/tpls/etc/nginx/nginx.conf#L90-L98) and works as expected. What are your response headers ?

**Comment by toredash** [comment]
Can't remember right now, but if you could try it in your environment, you should see it does not gzip that query.

It doesn't work since charset is missing, and either way, all calls to those files should be gzipped.

**Comment by crazy-max** [comment]
I have test this query `index.php?forceView=1&viewDataTable=VisitorLog&module=Live&action=getLastVisitsDetails&small=1&idSite=5&period=month&date=2019-04-16&showtitle=1&random=8752` and content is gzipped :

```
HTTP/2.0 200 OK
cache-control: no-store, must-revalidate
content-encoding: gzip
content-type: text/html; charset=utf-8
date: Thu, 02 May 2019 22:41:26 GMT
server: nginx
vary: Accept-Encoding
x-matomo-request-id: *****
X-Firefox-Spdy: h2
```

**Pull request closed without merging**
